services:
  register-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: register-server
    ports:
      - "8761:8761"
    networks:
      - backend
  config-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: config-server
    environment:
      - SPRING_PROFILES_ACTIVE=git,docker
    ports:
      - "8888:8888"
    networks:
      - backend
    depends_on:
      - register-server
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: user-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - register-server
      - config-server


  authentication-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: authentication-service
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - register-server
      - config-server

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: product-service
    ports:
      - "8083:8083"

    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - register-server
      - config-server



  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: inventory-service
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - register-server
      - config-server


  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: gateway-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:
      - register-server
      - config-server

  swagger-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: swagger-service
    ports:
      - "7777:7777"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:

      - register-server
      - config-server

  review-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: review-service
    ports:
      - "8089:8089"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:

      - register-server
      - config-server

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: payment-service
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:

      - register-server
      - config-server
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: order-service
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:

      - register-server
      - config-server
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: notification-service
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend
    depends_on:

      - register-server
      - config-server
  chatbot-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODULE_NAME: chatbot-service
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    extra_hosts:
      - "host.docker.internal:host-gateway" # 🌟 Required for Linux containers to find your host machine's ports
    networks:
      - backend
    depends_on:
      - register-server
      - config-server
      - chromadb
      - postgres

  chromadb:
    image: chromadb/chroma:latest
    container_name: standalone-chromadb
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    restart: always

  postgres:
    image: postgres:latest
    container_name: ecommerce_db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce_db
    networks:
      - backend
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - backend
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Internal communication
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      # Required configs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube_db
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

networks:
  backend:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  mongo_data:
  chroma-data: