services:
  redis:
    image: redis:7.2-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: always

  register-server:
    image: lnreddydev/register-server:latest
    ports:
      - "8761:8761"
    networks:
      - backend
      
  config-server:
    image: lnreddydev/config-server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=git,docker
    ports:
      - "8888:8888"
    networks:
      - backend
    depends_on:
      - register-server
  user-service:
    image: lnreddydev/user-service:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=docker,dev
    networks:
      - backend
    depends_on:
      - postgres
      - register-server
      - config-server


  authentication-service:
    image: lnreddydev/authentication-service:latest
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:
      - register-server
      - config-server

  product-service:
    image: lnreddydev/product-service:latest
    ports:
      - "8083:8083"

    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - backend
    depends_on:
      - redis
      - postgres
      - kafka
      - register-server
      - config-server



  inventory-service:
    image: lnreddydev/inventory-service:latest
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:
      - postgres
      - kafka
      - register-server
      - config-server


  gateway-service:
    image: lnreddydev/gateway-service:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:
      - register-server
      - config-server

  swagger-service:
    image: lnreddydev/swagger-service:latest
    ports:
      - "7777:7777"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev,docker
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
    networks:
      - backend
    depends_on:

      - register-server
      - config-server

  review-service:
    image: lnreddydev/review-service:latest
    ports:
      - "8089:8089"
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:
      - postgres
      - register-server
      - config-server

  payment-service:
    image: lnreddydev/payment-service:latest
    ports:
      - "8086:8086"
    env_file:
      - .env
    environment:

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:
      - postgres
      - kafka
      - register-server
      - config-server
  order-service:
    image: lnreddydev/order-service:latest
    ports:
      - "8084:8084"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:

      - register-server
      - config-server
  notification-service:
    image: lnreddydev/notification-service:latest
    ports:
      - "8088:8088"
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:

      - register-server
      - config-server
  cart-service:
    image: lnreddydev/cart-service:latest
    ports:
      - "8087:8087"
    env_file:
      - .env
    environment:
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    networks:
      - backend
    depends_on:
      - postgres
      - register-server
      - config-server
  chatbot-service:
    image: lnreddydev/chatbot-service:latest
    ports:
      - "9999:9999"
    env_file:
      - .env
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_AI_OLLAMA_BASE_URL=http://host.docker.internal:11434
      - SPRING_AI_VECTORSTORE_CHROMA_CLIENT_HOST=http://chromadb
      - SPRING_AI_VECTORSTORE_CHROMA_CLIENT_PORT=8000
      - EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE=http://register-server:8761/eureka/
      - SPRING_PROFILES_ACTIVE=dev,docker
    extra_hosts:
      - "host.docker.internal:host-gateway" # Required for Linux containers to find your host machine's ports
    networks:
      - backend
    depends_on:
      - register-server
      - config-server
      - chromadb
      - postgres

  chromadb:
    image: chromadb/chroma:latest
    container_name: standalone-chromadb
    ports:
      - "8000:8000"
    networks:
      - backend
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    restart: always

  postgres:
    image: postgres:latest
    container_name: ecommerce_db
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce_db
    networks:
      - backend
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - backend
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      # Define both entry points explicitly
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093'
      # CRITICAL: This is what Kafka tells the microservices to use for subsequent requests
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube_db
      SONAR_JDBC_USERNAME: admin
      SONAR_JDBC_PASSWORD: admin
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions


  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack_main
    ports:
      - "4566:4566"            # The main edge port for all AWS services (S3, SQS, etc.)
      - "4510-4559:4510-4559"  # Ports used for external service execution if needed
    environment:
      - SERVICES=s3,sqs        # Explicitly activate only the services you need to save RAM
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./data/localstack:/var/lib/localstack" # Persist your local AWS data structure
      - "/var/run/docker.sock:/var/run/docker.sock" # Allows LocalStack to spin up lambda containers if needed
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  mongo_data:
  chroma-data: