apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: cart-service
  name: cart-service
spec:
  ports:
    - name: "8087"
      port: 8087
      targetPort: 8087
  selector:
    io.kompose.service: cart-service
