apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: swagger-service
  name: swagger-service
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    io.kompose.service: swagger-service
