spring:
  application:
    name: chatbot-service

  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888


logging:
  level:
    org.springframework.ai: DEBUG
    org.springframework.web.client: DEBUG
    httpclient.wire: DEBUG
---
#  DOCKER CONTAINER NETWORK OVERRIDES
spring:
  config:
    activate:
      on-profile: docker
    # Tells the container to find the config server via its container mesh name
    import: optional:configserver:http://config-server:8888