spring:
  application:
    name: ecommerce




eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

# server port
server:
  port: 8761

#actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
