spring:
  application:
    name: config-server

#to select profile
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Narasimha-prog/microservices-remote-properties.git
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
#actuators
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8888